version: '3'

services:
  # db:
  #   container_name: db
  #   build:
  #     context: db
  #   ports:
  #     - "27017:27017"
  # api:
  #   container_name: api
  #   depends_on:
  #     - db
  #   build:
  #     context: api
  viz:
    container_name: viz
    # depends_on:
    #   - api
    build:
      context: viz
    ports:
      - "8050:8050"
